# dataset
dataset_name: 'mnist' # ['mnist','cifar10']
normal_class: [0]
known_outlier_class: [1,2]
ratio_known_normal: 0.0
ratio_known_outlier: 0.01
ratio_pollution: 0.1

# General setting
batch_size: 128
eta: 1


# training setting
epochs: 100
model_name: 'mnist_LeNet'
lr: 0.001
